### ISSUE TITLE
dothemath!

### ISSUE THREAD

**Issue by sh-dave** [Kode/kincmake#80]
https://github.com/Kode/kincmake/blob/5712893bcaac022a1491a47e3168ea96dfb0963e/src/main.ts#L449

I just tried to compile with vs2015 on a random old computer at work and that failed, b/c it tries to run a non existing vsvars64.bat instead of the vsvars32.bat. Is 32bit windows still relevant and this should be fixed kinda like `const dothemath = options.arch == Architecture.X86 ? false : true;`
?

**Comment by RobDangerous** [comment]
Not sure it's still relevant. I'll soon try to test that by switching the Haxe compiler to the 64bit version (already did so on the jscompat branch because some project grew too large).

**Comment by RobDangerous** [comment]
Forgot to add this one: https://www.youtube.com/watch?v=mlRWqqWay7c
